name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
  push:
    branches: [ main ]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "https://ghcr.io/$GITHUB_REPOSITORY:${GITHUB_SHA::7}" -t "https://ghcr.io/$GITHUB_REPOSITORY:latest"
    - name: Push the Docker image
      run: docker push -a "https://ghcr.io/$GITHUB_REPOSITORY"

