name: Docker Image CI

on:  
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Node.js CI"]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t "ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA::7}" -t "ghcr.io/${GITHUB_REPOSITORY,,}:latest"
    - name: Push the Docker image
      run: docker push -a "ghcr.io/${GITHUB_REPOSITORY,,}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


