name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t "ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA::7}" -t "ghcr.io/${GITHUB_REPOSITORY,,}:latest"
    - name: Push the Docker image
      run: docker push -a "ghcr.io/${GITHUB_REPOSITORY,,}"

